#' @importFrom Seurat CreateSeuratObject
#' @importFrom Seurat DefaultAssay
#' @importFrom Seurat as.SingleCellExperiment
#' @importFrom stringr str_c
#' @importFrom scDblFinder scDblFinder
#' @importFrom dplyr count
#' @importFrom dplyr mutate
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 ggtitle
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 ylab
#' @importFrom ggplot2 theme_classic
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 scale_fill_manual
